### ISSUE TITLE
Type stubs are missing return type annotations

### ISSUE THREAD

**Issue by jakob-keller** [tarasko/picows#27]
Thank you for creating picows!

I just started to work with this project and noticed that mypy (in strict mode) is complaining about calls to `WSTransport.wait_disconnected()`: 

`error: Call to untyped function "wait_disconnected" in typed context  [no-untyped-call]`

https://github.com/tarasko/picows/blob/29c1027f8a0d2e77afb354db4de6d8241d40a0ee/picows/picows.pyi#L105 does not have a return type annotation. The same is true for other methods in that stub file.

Could you please add these annotations in a future release? Thank you!

**Comment by tarasko** [comment]
Thank you for reporting this and for using picows :)

Apart from fixing the stub we should also add mypy check to the build pipeline.

**Comment by tarasko** [comment]
Fixed in 1.7.2
