### ISSUE TITLE
I have designed a new logo for picows

### ISSUE THREAD

**Issue by River-Shi** [tarasko/picows#28]
<img width="847" alt="picows" src="https://github.com/user-attachments/assets/5584d500-52f7-489e-b413-47872ac1026b">

**Comment by tarasko** [comment]
Haha, nice!
I used chatgpt to generate the current one. But yours is better! :) Indeed let's update it

**Comment by River-Shi** [comment]
> Haha, nice! I used chatgpt to generate the current one. But yours is better! :) Indeed let's update it

Here is the light and dark version. How can I send them to you?
<img width="847" alt="picows-dark" src="https://github.com/user-attachments/assets/cf7c40fd-790d-4827-900c-8f15eaf3793c">
<img width="847" alt="picows-light" src="https://github.com/user-attachments/assets/0c323dc7-6b87-40bc-b119-7285848bf2ab">
